cast type to java.nio.Buffer to flip()
hyperledger/fabric-chaincode-java pull request #207
Opened 2021-10-29 18:22 UTC by Sunxiai51

When starting java chaincode as a service with shim 2.2.3 on JDK8, `epochBytes.flip()` throws `java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()`, which would make the response of the invoke request from peer miss, and peer would report timeout.

2021-10-29 20:35 UTC, jkneubuh commented
I like this fix, this is a good update.   I do wonder if there are things we can do in the shim and/or project template to avoid similar errors in the future, or at least make it easier to troubleshoot.   For the targeted issue of this timeout, I think this is a good PR.  I'll address the general comments over in [Issue #2916](https://github.com/hyperledger/fabric/issues/2916).

2021-11-01 11:17 UTC, mbwhite commented
Thank you for the PR; however the main branch (2.4-beta) or the 2.2 release isn't supported for Java8, it's Java 11 or later.

2021-11-01 11:24 UTC, mbwhite requested changes
Is this an issue with Java11?

2022-03-21 10:00 UTC, mbwhite commented
Due to lack of activity I'm going to close this PR; please re-open if you you're able to do further work.

2022-03-21 10:00 UTC, closed without merging